# Define the goal
iroc_fleet_manager/AutonomyTestRobot[] robots
---
# Define the result
bool success
string message
iroc_mission_handler/MissionResult[] robots_results
---
# Define a feedback message
iroc_fleet_manager/WaypointMissionInfo info

