# Define the goal
iroc_mission_management/WaypointMissionRobot[] robots
---
# Define the result
bool success
string message
---
# Define a feedback message
string message
string status 
float64 mission_progress

string STATUS_TRAJECTORIES_LOADED = trajectories_loaded
string STATUS_EXECUTING = mission_executing 
string STATUS_PAUSED = mission_paused 
string STATUS_ABORTED = mission_aborted 
string STATUS_INVALID = mission_invalid 
