# Define the goal
iroc_fleet_manager/WaypointMissionRobot[] robots
---
# Define the result
bool success
string[] messages
iroc_fleet_manager/WaypointMissionRobotResult[] robots_results
---
# Define a feedback message
iroc_fleet_manager/WaypointMissionInfo info
