# Define the goal
iroc_mission_management/WaypointMissionRobot[] robots
---
# Define the result
bool success
string message
---
# Define a feedback message
iroc_mission_management/WaypointMissionInfo info
