# define "running instances" of plugins, there can be more than one for each
#
WaypointPlanner:
  address: "iroc_fleet_manager/WaypointPlanner" 
  name_space: "waypoint_planner" 
  action_type: "WaypointFleetManagerAction"
